PS-Resources-1.0
Encoding
FontAFM
FontFamily
FontOutline
FontPFM
mkpsresPrivate
.
Encoding
AdobeEncoding=C:\Program Files\MiKTeX\dvips\base\ad.enc
ASEXEncoding=C:\Program Files\MiKTeX\dvips\base\asex.enc
ASEXPEncoding=C:\Program Files\MiKTeX\dvips\base\asexp.enc
CorkEncoding=C:\Program Files\MiKTeX\dvips\base\cork.enc
DCEncoding=C:\Program Files\MiKTeX\dvips\base\dc.enc
DvipsEncoding=C:\Program Files\MiKTeX\dvips\base\dvips.enc
DvipsEncoding=C:\Program Files\MiKTeX\dvips\base\odvips.enc
ECEncoding=C:\Program Files\MiKTeX\dvips\base\ec.enc
ExtendedTeXEncoding=C:\Program Files\MiKTeX\dvips\base\extex.enc
FunkyEncoding=C:\Program Files\MiKTeX\dvips\base\funky.enc
StandardEncoding=C:\Program Files\MiKTeX\dvips\base\8a.enc
TeXBase1Encoding=C:\Program Files\MiKTeX\dvips\base\8r.enc
TeXMathExtensionEncoding=C:\Program Files\MiKTeX\dvips\base\texmext.enc
TeXMathItalicEncoding=C:\Program Files\MiKTeX\dvips\base\texmital.enc
TeXMathSymbolEncoding=C:\Program Files\MiKTeX\dvips\base\texmsym.enc
TeXnANSIEncoding=C:\Program Files\MiKTeX\dvips\ly1\texnansi.enc
XL2encoding=C:\Program Files\MiKTeX\dvips\base\xl2.enc
XT2encoding=C:\Program Files\MiKTeX\dvips\base\xt2.enc
.
FontAFM
AvantGarde-Book=C:\Program Files\MiKTeX\fonts\afm\adobe\avantgar\pagk8a.afm
AvantGarde-BookOblique=C:\Program Files\MiKTeX\fonts\afm\adobe\avantgar\pagko8a.afm
AvantGarde-Demi=C:\Program Files\MiKTeX\fonts\afm\adobe\avantgar\pagd8a.afm
AvantGarde-DemiOblique=C:\Program Files\MiKTeX\fonts\afm\adobe\avantgar\pagdo8a.afm
CenturySchL-Bold=c:\localt~1\gs\fonts\c059016l.afm
CenturySchL-Bold=C:\Program Files\MiKTeX\fonts\afm\urw\ncntrsbk\uncb8a.afm
CenturySchL-BoldItal=c:\localt~1\gs\fonts\c059036l.afm
CenturySchL-BoldItal=C:\Program Files\MiKTeX\fonts\afm\urw\ncntrsbk\uncbi8a.afm
CenturySchL-Ital=c:\localt~1\gs\fonts\c059033l.afm
CenturySchL-Ital=C:\Program Files\MiKTeX\fonts\afm\urw\ncntrsbk\uncri8a.afm
CenturySchL-Roma=c:\localt~1\gs\fonts\c059013l.afm
CenturySchL-Roma=C:\Program Files\MiKTeX\fonts\afm\urw\ncntrsbk\uncr8a.afm
CharterBT-Bold=C:\LocalTeXMF\fonts\afm\Wolfram\CharterBT-Bold.afm
CharterBT-Bold=c:\localt~1\gs\fonts\bchb.afm
CharterBT-BoldItalic=C:\LocalTeXMF\fonts\afm\Wolfram\CharterBT-BoldItalic.afm
CharterBT-BoldItalic=c:\localt~1\gs\fonts\bchbi.afm
CharterBT-Italic=C:\LocalTeXMF\fonts\afm\Wolfram\CharterBT-Italic.afm
CharterBT-Italic=c:\localt~1\gs\fonts\bchri.afm
CharterBT-Roman=C:\LocalTeXMF\fonts\afm\Wolfram\CharterBT-Roman.afm
CharterBT-Roman=c:\localt~1\gs\fonts\bchr.afm
CMB10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmb10.afm
CMBSY10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmbsy10.afm
CMBSY5=C:\Program Files\MiKTeX\fonts\afm\ams\cmextra\cmbsy5.afm
CMBSY7=C:\Program Files\MiKTeX\fonts\afm\ams\cmextra\cmbsy7.afm
CMBX10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmbx10.afm
CMBX12=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmbx12.afm
CMBX5=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmbx5.afm
CMBX6=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmbx6.afm
CMBX7=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmbx7.afm
CMBX8=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmbx8.afm
CMBX9=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmbx9.afm
CMBXSL10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmbxsl10.afm
CMBXTI10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmbxti10.afm
CMCSC10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmcsc10.afm
CMDUNH10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmdunh10.afm
CMEX10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmex10.afm
CMFF10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmff10.afm
CMFI10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmfi10.afm
CMFIB8=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmfib8.afm
CMINCH=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cminch.afm
CMITT10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmitt10.afm
CMMI10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmmi10.afm
CMMI12=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmmi12.afm
CMMI5=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmmi5.afm
CMMI6=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmmi6.afm
CMMI7=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmmi7.afm
CMMI8=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmmi8.afm
CMMI9=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmmi9.afm
CMMIB10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmmib10.afm
CMMIB5=C:\Program Files\MiKTeX\fonts\afm\ams\cmextra\cmmib5.afm
CMMIB7=C:\Program Files\MiKTeX\fonts\afm\ams\cmextra\cmmib7.afm
CMR10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmr10.afm
CMR12=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmr12.afm
CMR17=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmr17.afm
CMR5=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmr5.afm
CMR6=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmr6.afm
CMR7=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmr7.afm
CMR8=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmr8.afm
CMR9=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmr9.afm
CMSL10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmsl10.afm
CMSL12=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmsl12.afm
CMSL8=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmsl8.afm
CMSL9=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmsl9.afm
CMSLTT10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmsltt10.afm
CMSS10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmss10.afm
CMSS12=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmss12.afm
CMSS17=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmss17.afm
CMSS8=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmss8.afm
CMSS9=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmss9.afm
CMSSBX10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmssbx10.afm
CMSSDC10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmssdc10.afm
CMSSI10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmssi10.afm
CMSSI12=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmssi12.afm
CMSSI17=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmssi17.afm
CMSSI8=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmssi8.afm
CMSSI9=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmssi9.afm
CMSSQ8=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmssq8.afm
CMSSQI8=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmssqi8.afm
CMSY10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmsy10.afm
CMSY5=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmsy5.afm
CMSY6=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmsy6.afm
CMSY7=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmsy7.afm
CMSY8=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmsy8.afm
CMSY9=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmsy9.afm
CMTCSC10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmtcsc10.afm
CMTEX10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmtex10.afm
CMTEX8=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmtex8.afm
CMTEX9=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmtex9.afm
CMTI10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmti10.afm
CMTI12=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmti12.afm
CMTI7=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmti7.afm
CMTI8=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmti8.afm
CMTI9=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmti9.afm
CMTT10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmtt10.afm
CMTT12=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmtt12.afm
CMTT8=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmtt8.afm
CMTT9=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmtt9.afm
CMU10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmu10.afm
CMVTT10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\cmvtt10.afm
Courier=C:\LocalTeXMF\fonts\afm\Wolfram\Courier.afm
Courier=C:\Program Files\MiKTeX\fonts\afm\adobe\courier\pcrr8a.afm
Courier-Bold=C:\LocalTeXMF\fonts\afm\Wolfram\Courier-Bold.afm
Courier-Bold=C:\Program Files\MiKTeX\fonts\afm\adobe\courier\pcrb8a.afm
Courier-BoldOblique=C:\LocalTeXMF\fonts\afm\Wolfram\Courier-BoldOblique.afm
Courier-BoldOblique=C:\Program Files\MiKTeX\fonts\afm\adobe\courier\pcrbo8a.afm
Courier-Oblique=C:\LocalTeXMF\fonts\afm\Wolfram\Courier-Oblique.afm
Courier-Oblique=C:\Program Files\MiKTeX\fonts\afm\adobe\courier\pcrro8a.afm
Cyrillic=c:\localt~1\gs\fonts\fcyr.afm
Cyrillic-Italic=c:\localt~1\gs\fonts\fcyri.afm
Dingbats=c:\localt~1\gs\fonts\d050000l.afm
Dingbats=C:\Program Files\MiKTeX\fonts\afm\urw\zapfding\uzdr.afm
Helvetica=C:\LocalTeXMF\fonts\afm\Wolfram\Helvetica.afm
Helvetica=C:\Program Files\MiKTeX\fonts\afm\adobe\helvetic\phvr8a.afm
Helvetica-Bold=C:\LocalTeXMF\fonts\afm\Wolfram\Helvetica-Bold.afm
Helvetica-Bold=C:\Program Files\MiKTeX\fonts\afm\adobe\helvetic\phvb8a.afm
Helvetica-BoldOblique=C:\LocalTeXMF\fonts\afm\Wolfram\Helvetica-BoldOblique.afm
Helvetica-BoldOblique=C:\Program Files\MiKTeX\fonts\afm\adobe\helvetic\phvbo8a.afm
Helvetica-Condensed-Light=C:\Program Files\MiKTeX\fonts\afm\adobe\helvetic\phvl8ac.afm
Helvetica-Condensed-Light=C:\Program Files\MiKTeX\fonts\afm\adobe\helvetic\phvlr8ac.afm
Helvetica-Condensed-LightObl=C:\Program Files\MiKTeX\fonts\afm\adobe\helvetic\phvlo8ac.afm
Helvetica-Light=C:\Program Files\MiKTeX\fonts\afm\adobe\helvetic\phvl8a.afm
Helvetica-LightOblique=C:\Program Files\MiKTeX\fonts\afm\adobe\helvetic\phvlo8a.afm
Helvetica-Narrow=C:\Program Files\MiKTeX\fonts\afm\adobe\helvetic\phvr8an.afm
Helvetica-Narrow-Bold=C:\Program Files\MiKTeX\fonts\afm\adobe\helvetic\phvb8an.afm
Helvetica-Narrow-BoldOblique=C:\Program Files\MiKTeX\fonts\afm\adobe\helvetic\phvbo8an.afm
Helvetica-Narrow-Oblique=C:\Program Files\MiKTeX\fonts\afm\adobe\helvetic\phvro8an.afm
Helvetica-Oblique=C:\LocalTeXMF\fonts\afm\Wolfram\Helvetica-Oblique.afm
Helvetica-Oblique=C:\Program Files\MiKTeX\fonts\afm\adobe\helvetic\phvro8a.afm
LASY10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\lasy10.afm
LASY5=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\lasy5.afm
LASY6=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\lasy6.afm
LASY7=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\lasy7.afm
LASY8=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\lasy8.afm
LASY9=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\lasy9.afm
LASYB10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\lasyb10.afm
LCIRCLE10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\lcircle1.afm
LCIRCLEW10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\lcirclew.afm
LCMSS8=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\lcmss8.afm
LCMSSB8=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\lcmssb8.afm
LCMSSI8=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\lcmssi8.afm
LINE10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\line10.afm
LINEW10=C:\Program Files\MiKTeX\fonts\afm\bluesky\cm\linew10.afm
LucidaBlackletter=C:\Program Files\MiKTeX\fonts\afm\yandy\lucida\lbl.afm
LucidaBright=C:\Program Files\MiKTeX\fonts\afm\yandy\lubright\lbr.afm
LucidaBright-Demi=C:\Program Files\MiKTeX\fonts\afm\yandy\lubright\lbd.afm
LucidaBright-DemiItalic=C:\Program Files\MiKTeX\fonts\afm\yandy\lubright\lbdi.afm
LucidaBright-Italic=C:\Program Files\MiKTeX\fonts\afm\yandy\lubright\lbi.afm
LucidaBright-Oblique=C:\Program Files\MiKTeX\fonts\afm\yandy\lubright\lbsl.afm
LucidaBrightSmallcaps=C:\Program Files\MiKTeX\fonts\afm\yandy\lubright\lbrsc.afm
LucidaBrightSmallcaps-Demi=C:\Program Files\MiKTeX\fonts\afm\yandy\lubright\lbdsc.afm
LucidaCalligraphy-Italic=C:\Program Files\MiKTeX\fonts\afm\yandy\lucida\lbc.afm
LucidaCasual=C:\Program Files\MiKTeX\fonts\afm\yandy\lucida\lbkr.afm
LucidaCasual-Italic=C:\Program Files\MiKTeX\fonts\afm\yandy\lucida\lbki.afm
LucidaFax=C:\Program Files\MiKTeX\fonts\afm\yandy\lucidfax\lfr.afm
LucidaFax-Demi=C:\Program Files\MiKTeX\fonts\afm\yandy\lucidfax\lfd.afm
LucidaFax-DemiItalic=C:\Program Files\MiKTeX\fonts\afm\yandy\lucidfax\lfdi.afm
LucidaFax-Italic=C:\Program Files\MiKTeX\fonts\afm\yandy\lucidfax\lfi.afm
LucidaHandwriting-Italic=C:\Program Files\MiKTeX\fonts\afm\yandy\lucida\lbh.afm
LucidaNewMath-AltDemiItalic=C:\Program Files\MiKTeX\fonts\afm\yandy\lumath\lbmdo.afm
LucidaNewMath-AltDemiItalic=C:\Program Files\MiKTeX\fonts\afm\yandy\lumath\lbmdotex.afm
LucidaNewMath-AltItalic=C:\Program Files\MiKTeX\fonts\afm\yandy\lumath\lbmo.afm
LucidaNewMath-AltItalic=C:\Program Files\MiKTeX\fonts\afm\yandy\lumath\lbmotex.afm
LucidaNewMath-Arrows=C:\Program Files\MiKTeX\fonts\afm\yandy\lumath\lbma.afm
LucidaNewMath-Arrows=C:\Program Files\MiKTeX\fonts\afm\yandy\lumath\lbmatex.afm
LucidaNewMath-Arrows-Demi=C:\Program Files\MiKTeX\fonts\afm\yandy\lumath\lbmad.afm
LucidaNewMath-Arrows-Demi=C:\Program Files\MiKTeX\fonts\afm\yandy\lumath\lbmadtex.afm
LucidaNewMath-Demibold=C:\Program Files\MiKTeX\fonts\afm\yandy\lumath\lbmd.afm
LucidaNewMath-Demibold=C:\Program Files\MiKTeX\fonts\afm\yandy\lumath\lbmdtex.afm
LucidaNewMath-DemiItalic=C:\Program Files\MiKTeX\fonts\afm\yandy\lumath\lbmdi.afm
LucidaNewMath-DemiItalic=C:\Program Files\MiKTeX\fonts\afm\yandy\lumath\lbmditex.afm
LucidaNewMath-Extension=C:\Program Files\MiKTeX\fonts\afm\yandy\lumath\lbme.afm
LucidaNewMath-Extension=C:\Program Files\MiKTeX\fonts\afm\yandy\lumath\lbmetex.afm
LucidaNewMath-Italic=C:\Program Files\MiKTeX\fonts\afm\yandy\lumath\lbmi.afm
LucidaNewMath-Italic=C:\Program Files\MiKTeX\fonts\afm\yandy\lumath\lbmitex.afm
LucidaNewMath-Roman=C:\Program Files\MiKTeX\fonts\afm\yandy\lumath\lbmr.afm
LucidaNewMath-Roman=C:\Program Files\MiKTeX\fonts\afm\yandy\lumath\lbmrtex.afm
LucidaNewMath-Symbol=C:\Program Files\MiKTeX\fonts\afm\yandy\lumath\lbms.afm
LucidaNewMath-Symbol=C:\Program Files\MiKTeX\fonts\afm\yandy\lumath\lbmstex.afm
LucidaNewMath-Symbol-Demi=C:\Program Files\MiKTeX\fonts\afm\yandy\lumath\lbmsd.afm
LucidaNewMath-Symbol-Demi=C:\Program Files\MiKTeX\fonts\afm\yandy\lumath\lbmsdtex.afm
LucidaSans=C:\Program Files\MiKTeX\fonts\afm\yandy\lucsans\lsr.afm
LucidaSans-Bold=C:\Program Files\MiKTeX\fonts\afm\yandy\lucsans\lsb.afm
LucidaSans-BoldItalic=C:\Program Files\MiKTeX\fonts\afm\yandy\lucsans\lsbi.afm
LucidaSans-Demi=C:\Program Files\MiKTeX\fonts\afm\yandy\lucsans\lsd.afm
LucidaSans-DemiItalic=C:\Program Files\MiKTeX\fonts\afm\yandy\lucsans\lsdi.afm
LucidaSans-Italic=C:\Program Files\MiKTeX\fonts\afm\yandy\lucsans\lsi.afm
LucidaSans-Typewriter=C:\Program Files\MiKTeX\fonts\afm\yandy\lucsans\lstr.afm
LucidaSans-TypewriterBold=C:\Program Files\MiKTeX\fonts\afm\yandy\lucsans\lstb.afm
LucidaSans-TypewriterBoldOblique=C:\Program Files\MiKTeX\fonts\afm\yandy\lucsans\lstbo.afm
LucidaSans-TypewriterOblique=C:\Program Files\MiKTeX\fonts\afm\yandy\lucsans\lsto.afm
LucidaTypewriter=C:\Program Files\MiKTeX\fonts\afm\yandy\lucida\lbtr.afm
LucidaTypewriterBold=C:\Program Files\MiKTeX\fonts\afm\yandy\lucida\lbtb.afm
LucidaTypewriterBoldOblique=C:\Program Files\MiKTeX\fonts\afm\yandy\lucida\lbtbo.afm
LucidaTypewriterOblique=C:\Program Files\MiKTeX\fonts\afm\yandy\lucida\lbto.afm
Math1=C:\LocalTeXMF\fonts\afm\Wolfram\Math1.afm
Math1-Bold=C:\LocalTeXMF\fonts\afm\Wolfram\Math1-Bold.afm
Math1Mono=C:\LocalTeXMF\fonts\afm\Wolfram\Math1Mono.afm
Math1Mono-Bold=C:\LocalTeXMF\fonts\afm\Wolfram\Math1Mono-Bold.afm
Math2=C:\LocalTeXMF\fonts\afm\Wolfram\Math2.afm
Math2-Bold=C:\LocalTeXMF\fonts\afm\Wolfram\Math2-Bold.afm
Math2Mono=C:\LocalTeXMF\fonts\afm\Wolfram\Math2Mono.afm
Math2Mono-Bold=C:\LocalTeXMF\fonts\afm\Wolfram\Math2Mono-Bold.afm
Math3=C:\LocalTeXMF\fonts\afm\Wolfram\Math3.afm
Math3-Bold=C:\LocalTeXMF\fonts\afm\Wolfram\Math3-Bold.afm
Math3Mono=C:\LocalTeXMF\fonts\afm\Wolfram\Math3Mono.afm
Math3Mono-Bold=C:\LocalTeXMF\fonts\afm\Wolfram\Math3Mono-Bold.afm
Math4=C:\LocalTeXMF\fonts\afm\Wolfram\Math4.afm
Math4-Bold=C:\LocalTeXMF\fonts\afm\Wolfram\Math4-Bold.afm
Math4Mono=C:\LocalTeXMF\fonts\afm\Wolfram\Math4Mono.afm
Math4Mono-Bold=C:\LocalTeXMF\fonts\afm\Wolfram\Math4Mono-Bold.afm
Math5=C:\LocalTeXMF\fonts\afm\Wolfram\Math5.afm
Math5-Bold=C:\LocalTeXMF\fonts\afm\Wolfram\Math5-Bold.afm
Math5Mono=C:\LocalTeXMF\fonts\afm\Wolfram\Math5Mono.afm
Math5Mono-Bold=C:\LocalTeXMF\fonts\afm\Wolfram\Math5Mono-Bold.afm
MTEX=C:\Program Files\MiKTeX\fonts\afm\yandy\mathtime\mtex.afm
MTEXB=C:\Program Files\MiKTeX\fonts\afm\yandy\mathplus\mtexb.afm
MTEXH=C:\Program Files\MiKTeX\fonts\afm\yandy\mathplus\mtexh.afm
MTGU=C:\Program Files\MiKTeX\fonts\afm\yandy\mathplus\mtgu.afm
MTGUB=C:\Program Files\MiKTeX\fonts\afm\yandy\mathplus\mtgub.afm
MTLS=C:\Program Files\MiKTeX\fonts\afm\yandy\mathplus\mtls.afm
MTLSB=C:\Program Files\MiKTeX\fonts\afm\yandy\mathplus\mtlsb.afm
MTMI=C:\Program Files\MiKTeX\fonts\afm\yandy\mathtime\mtmi.afm
MTMIB=C:\Program Files\MiKTeX\fonts\afm\yandy\mathplus\mtmib.afm
MTMIH=C:\Program Files\MiKTeX\fonts\afm\yandy\mathplus\mtmih.afm
MTMS=C:\Program Files\MiKTeX\fonts\afm\yandy\mathplus\mtms.afm
MTMSB=C:\Program Files\MiKTeX\fonts\afm\yandy\mathplus\mtmsb.afm
MTMUB=C:\Program Files\MiKTeX\fonts\afm\yandy\mathplus\mtmub.afm
MTMUH=C:\Program Files\MiKTeX\fonts\afm\yandy\mathplus\mtmuh.afm
MTSY=C:\Program Files\MiKTeX\fonts\afm\yandy\mathtime\mtsy.afm
MTSYB=C:\Program Files\MiKTeX\fonts\afm\yandy\mathplus\mtsyb.afm
MTSYH=C:\Program Files\MiKTeX\fonts\afm\yandy\mathplus\mtsyh.afm
MTSYN=C:\Program Files\MiKTeX\fonts\afm\yandy\mathplus\mtsyn.afm
NewMilleniumSchlbk-BoldItalicSH=c:\localt~1\gs\fonts\nemsbis_.afm
NimbusMonL-Bold=c:\localt~1\gs\fonts\n022004l.afm
NimbusMonL-Bold=C:\Program Files\MiKTeX\fonts\afm\urw\courier\ucrb8a.afm
NimbusMonL-BoldObli=c:\localt~1\gs\fonts\n022024l.afm
NimbusMonL-BoldObli=C:\Program Files\MiKTeX\fonts\afm\urw\courier\ucrbo8a.afm
NimbusMonL-Regu=c:\localt~1\gs\fonts\n022003l.afm
NimbusMonL-Regu=C:\Program Files\MiKTeX\fonts\afm\urw\courier\ucrr8a.afm
NimbusMonL-ReguObli=c:\localt~1\gs\fonts\n022023l.afm
NimbusMonL-ReguObli=C:\Program Files\MiKTeX\fonts\afm\urw\courier\ucrro8a.afm
NimbusRomanNo9L-Regular=C:\Program Files\MiKTeX\fonts\afm\urw\nimbus\unmr8a.afm
NimbusRomNo9L-Medi=c:\localt~1\gs\fonts\n021004l.afm
NimbusRomNo9L-Medi=C:\Program Files\MiKTeX\fonts\afm\urw\times\utmb8a.afm
NimbusRomNo9L-MediItal=c:\localt~1\gs\fonts\n021024l.afm
NimbusRomNo9L-MediItal=C:\Program Files\MiKTeX\fonts\afm\urw\times\utmbi8a.afm
NimbusRomNo9L-Regu=c:\localt~1\gs\fonts\n021003l.afm
NimbusRomNo9L-Regu=C:\Program Files\MiKTeX\fonts\afm\urw\times\utmr8a.afm
NimbusRomNo9L-ReguItal=c:\localt~1\gs\fonts\n021023l.afm
NimbusRomNo9L-ReguItal=C:\Program Files\MiKTeX\fonts\afm\urw\times\utmri8a.afm
NimbusSanL-Bold=c:\localt~1\gs\fonts\n019004l.afm
NimbusSanL-Bold=C:\Program Files\MiKTeX\fonts\afm\urw\helvetic\uhvb8a.afm
NimbusSanL-BoldCond=c:\localt~1\gs\fonts\n019044l.afm
NimbusSanL-BoldCond=C:\Program Files\MiKTeX\fonts\afm\urw\helvetic\uhvb8ac.afm
NimbusSanL-BoldCond=C:\Program Files\MiKTeX\fonts\afm\urw\helvetic\uhvb8an.afm
NimbusSanL-BoldCond=C:\Program Files\MiKTeX\fonts\afm\urw\helvetic\uhvbrc8a.afm
NimbusSanL-BoldCondItal=c:\localt~1\gs\fonts\n019064l.afm
NimbusSanL-BoldCondItal=C:\Program Files\MiKTeX\fonts\afm\urw\helvetic\uhvbo8ac.afm
NimbusSanL-BoldCondItal=C:\Program Files\MiKTeX\fonts\afm\urw\helvetic\uhvri8an.afm
NimbusSanL-BoldCondItal=C:\Program Files\MiKTeX\fonts\afm\urw\helvetic\uhvroc8a.afm
NimbusSanL-BoldItal=c:\localt~1\gs\fonts\n019024l.afm
NimbusSanL-BoldItal=C:\Program Files\MiKTeX\fonts\afm\urw\helvetic\uhvbi8a.afm
NimbusSanL-BoldItal=C:\Program Files\MiKTeX\fonts\afm\urw\helvetic\uhvbo8a.afm
NimbusSanL-Regu=c:\localt~1\gs\fonts\n019003l.afm
NimbusSanL-Regu=C:\Program Files\MiKTeX\fonts\afm\urw\helvetic\uhvr8a.afm
NimbusSanL-ReguCond=c:\localt~1\gs\fonts\n019043l.afm
NimbusSanL-ReguCond=C:\Program Files\MiKTeX\fonts\afm\urw\helvetic\uhvr8ac.afm
NimbusSanL-ReguCond=C:\Program Files\MiKTeX\fonts\afm\urw\helvetic\uhvr8an.afm
NimbusSanL-ReguCond=C:\Program Files\MiKTeX\fonts\afm\urw\helvetic\uhvrrc8a.afm
NimbusSanL-ReguCondItal=c:\localt~1\gs\fonts\n019063l.afm
NimbusSanL-ReguCondItal=C:\Program Files\MiKTeX\fonts\afm\urw\helvetic\uhvboc8a.afm
NimbusSanL-ReguCondItal=C:\Program Files\MiKTeX\fonts\afm\urw\helvetic\uhvro8ac.afm
NimbusSanL-ReguItal=c:\localt~1\gs\fonts\n019023l.afm
NimbusSanL-ReguItal=C:\Program Files\MiKTeX\fonts\afm\urw\helvetic\uhvri8a.afm
NimbusSanL-ReguItal=C:\Program Files\MiKTeX\fonts\afm\urw\helvetic\uhvro8a.afm
NimbusSansL-Regular=C:\Program Files\MiKTeX\fonts\afm\urw\nimbus\unmrs8a.afm
OmegaSerifArabicOne=C:\Program Files\MiKTeX\fonts\afm\public\omega\omsea1.afm
OmegaSerifArabicOne-Bold=C:\Program Files\MiKTeX\fonts\afm\public\omega\omsea1b.afm
OmegaSerifArabicThree=C:\Program Files\MiKTeX\fonts\afm\public\omega\omsea3.afm
OmegaSerifArabicThree-Bold=C:\Program Files\MiKTeX\fonts\afm\public\omega\omsea3b.afm
OmegaSerifArabicTwo=C:\Program Files\MiKTeX\fonts\afm\public\omega\omsea2.afm
OmegaSerifArabicTwo-Bold=C:\Program Files\MiKTeX\fonts\afm\public\omega\omsea2b.afm
OmegaSerifArmenian=C:\Program Files\MiKTeX\fonts\afm\public\omega\omseha.afm
OmegaSerifCommon=C:\Program Files\MiKTeX\fonts\afm\public\omega\omseco.afm
OmegaSerifCommon-Bold=C:\Program Files\MiKTeX\fonts\afm\public\omega\omsecob.afm
OmegaSerifCommon-BoldItalic=C:\Program Files\MiKTeX\fonts\afm\public\omega\omsecobi.afm
OmegaSerifCommon-Italic=C:\Program Files\MiKTeX\fonts\afm\public\omega\omsecoi.afm
OmegaSerifCyrillic=C:\Program Files\MiKTeX\fonts\afm\public\omega\omsecy.afm
OmegaSerifCyrillicExtended=C:\Program Files\MiKTeX\fonts\afm\public\omega\omsecx.afm
OmegaSerifGreek=C:\Program Files\MiKTeX\fonts\afm\public\omega\omsegr.afm
OmegaSerifGreek-Bold=C:\Program Files\MiKTeX\fonts\afm\public\omega\omsegrb.afm
OmegaSerifGreek-BoldItalic=C:\Program Files\MiKTeX\fonts\afm\public\omega\omsegrbi.afm
OmegaSerifGreek-Italic=C:\Program Files\MiKTeX\fonts\afm\public\omega\omsegri.afm
OmegaSerifHebrew=C:\Program Files\MiKTeX\fonts\afm\public\omega\omsehe.afm
OmegaSerifIPA=C:\Program Files\MiKTeX\fonts\afm\public\omega\omseip.afm
OmegaSerifLatin=C:\Program Files\MiKTeX\fonts\afm\public\omega\omsela.afm
OmegaSerifLatin-Bold=C:\Program Files\MiKTeX\fonts\afm\public\omega\omselab.afm
OmegaSerifLatin-BoldItalic=C:\Program Files\MiKTeX\fonts\afm\public\omega\omselabi.afm
OmegaSerifLatin-Italic=C:\Program Files\MiKTeX\fonts\afm\public\omega\omselai.afm
OmegaSerifTifinagh=C:\Program Files\MiKTeX\fonts\afm\public\omega\omseti.afm
Palatino-Bold=C:\Program Files\MiKTeX\fonts\afm\adobe\palatino\pplb8a.afm
Palatino-BoldItalic=C:\Program Files\MiKTeX\fonts\afm\adobe\palatino\pplbi8a.afm
Palatino-Italic=C:\Program Files\MiKTeX\fonts\afm\adobe\palatino\pplri8a.afm
Palatino-Roman=C:\Program Files\MiKTeX\fonts\afm\adobe\palatino\pplr8a.afm
RMTMI=C:\Program Files\MiKTeX\fonts\afm\yandy\mathtime\rmtmi.afm
RMTMIB=C:\Program Files\MiKTeX\fonts\afm\yandy\mathplus\rmtmib.afm
RMTMIH=C:\Program Files\MiKTeX\fonts\afm\yandy\mathplus\rmtmih.afm
RMTMUB=C:\Program Files\MiKTeX\fonts\afm\yandy\mathplus\rmtmub.afm
RMTMUH=C:\Program Files\MiKTeX\fonts\afm\yandy\mathplus\rmtmuh.afm
StandardSymL=c:\localt~1\gs\fonts\s050000l.afm
StandardSymL=C:\Program Files\MiKTeX\fonts\afm\urw\symbol\usyr.afm
Symbol=C:\Program Files\MiKTeX\fonts\afm\adobe\symbol\psyb.afm
Symbol=C:\Program Files\MiKTeX\fonts\afm\adobe\symbol\psyr.afm
Times-Bold=C:\LocalTeXMF\fonts\afm\Wolfram\Times-Bold.afm
Times-Bold=C:\Program Files\MiKTeX\fonts\afm\adobe\times\ptmb8a.afm
Times-BoldItalic=C:\LocalTeXMF\fonts\afm\Wolfram\Times-BoldItalic.afm
Times-BoldItalic=C:\Program Files\MiKTeX\fonts\afm\adobe\times\ptmbi8a.afm
Times-Italic=C:\LocalTeXMF\fonts\afm\Wolfram\Times-Italic.afm
Times-Italic=C:\Program Files\MiKTeX\fonts\afm\adobe\times\ptmri8a.afm
Times-Roman=C:\LocalTeXMF\fonts\afm\Wolfram\Times-Roman.afm
Times-Roman=C:\Program Files\MiKTeX\fonts\afm\adobe\times\ptmr8a.afm
URWAntiquaT-RegularCondensed=c:\localt~1\gs\fonts\u003043t.afm
URWAntiquaT-RegularCondensed=C:\Program Files\MiKTeX\fonts\afm\urw\antiqua\uaqr8ac.afm
URWBookmanL-DemiBold=c:\localt~1\gs\fonts\b018015l.afm
URWBookmanL-DemiBold=C:\Program Files\MiKTeX\fonts\afm\urw\bookman\ubkb8a.afm
URWBookmanL-DemiBold=C:\Program Files\MiKTeX\fonts\afm\urw\bookman\ubkd8a.afm
URWBookmanL-DemiBoldItal=c:\localt~1\gs\fonts\b018035l.afm
URWBookmanL-DemiBoldItal=C:\Program Files\MiKTeX\fonts\afm\urw\bookman\ubkbi8a.afm
URWBookmanL-DemiBoldItal=C:\Program Files\MiKTeX\fonts\afm\urw\bookman\ubkdi8a.afm
URWBookmanL-Ligh=c:\localt~1\gs\fonts\b018012l.afm
URWBookmanL-Ligh=C:\Program Files\MiKTeX\fonts\afm\urw\bookman\ubkl8a.afm
URWBookmanL-Ligh=C:\Program Files\MiKTeX\fonts\afm\urw\bookman\ubkr8a.afm
URWBookmanL-LighItal=c:\localt~1\gs\fonts\b018032l.afm
URWBookmanL-LighItal=C:\Program Files\MiKTeX\fonts\afm\urw\bookman\ubkli8a.afm
URWBookmanL-LighItal=C:\Program Files\MiKTeX\fonts\afm\urw\bookman\ubkri8a.afm
URWChanceryL-MediItal=c:\localt~1\gs\fonts\z003034l.afm
URWChanceryL-MediItal=C:\Program Files\MiKTeX\fonts\afm\urw\zapfchan\uzcmi8a.afm
URWGothicL-Book=c:\localt~1\gs\fonts\a010013l.afm
URWGothicL-Book=C:\Program Files\MiKTeX\fonts\afm\urw\avantgar\uagk8a.afm
URWGothicL-Book=C:\Program Files\MiKTeX\fonts\afm\urw\avantgar\uagr8a.afm
URWGothicL-BookObli=c:\localt~1\gs\fonts\a010033l.afm
URWGothicL-BookObli=C:\Program Files\MiKTeX\fonts\afm\urw\avantgar\uagko8a.afm
URWGothicL-BookObli=C:\Program Files\MiKTeX\fonts\afm\urw\avantgar\uagri8a.afm
URWGothicL-Demi=c:\localt~1\gs\fonts\a010015l.afm
URWGothicL-Demi=C:\Program Files\MiKTeX\fonts\afm\urw\avantgar\uagb8a.afm
URWGothicL-Demi=C:\Program Files\MiKTeX\fonts\afm\urw\avantgar\uagd8a.afm
URWGothicL-DemiObli=c:\localt~1\gs\fonts\a010035l.afm
URWGothicL-DemiObli=C:\Program Files\MiKTeX\fonts\afm\urw\avantgar\uagbi8a.afm
URWGothicL-DemiObli=C:\Program Files\MiKTeX\fonts\afm\urw\avantgar\uagdo8a.afm
URWGroteskT-Bold=c:\localt~1\gs\fonts\u004006t.afm
URWGroteskT-Bold=C:\Program Files\MiKTeX\fonts\afm\urw\grotesq\ugqb8a.afm
URWPalladioL-Bold=c:\localt~1\gs\fonts\p052004l.afm
URWPalladioL-Bold=C:\Program Files\MiKTeX\fonts\afm\urw\palatino\uplb8a.afm
URWPalladioL-BoldItal=c:\localt~1\gs\fonts\p052024l.afm
URWPalladioL-BoldItal=C:\Program Files\MiKTeX\fonts\afm\urw\palatino\uplbi8a.afm
URWPalladioL-Ital=c:\localt~1\gs\fonts\p052023l.afm
URWPalladioL-Ital=C:\Program Files\MiKTeX\fonts\afm\urw\palatino\uplri8a.afm
URWPalladioL-Roma=c:\localt~1\gs\fonts\p052003l.afm
URWPalladioL-Roma=C:\Program Files\MiKTeX\fonts\afm\urw\palatino\uplr8a.afm
Utopia-Bold=C:\LocalTeXMF\fonts\afm\Wolfram\Utopia-Bold.afm
Utopia-Bold=C:\Program Files\MiKTeX\fonts\afm\adobe\utopia\putb8a.afm
Utopia-BoldItalic=C:\LocalTeXMF\fonts\afm\Wolfram\Utopia-BoldItalic.afm
Utopia-BoldItalic=C:\Program Files\MiKTeX\fonts\afm\adobe\utopia\putbi8a.afm
Utopia-Italic=C:\LocalTeXMF\fonts\afm\Wolfram\Utopia-Italic.afm
Utopia-Italic=C:\Program Files\MiKTeX\fonts\afm\adobe\utopia\putri8a.afm
Utopia-Regular=C:\LocalTeXMF\fonts\afm\Wolfram\Utopia-Regular.afm
Utopia-Regular=C:\Program Files\MiKTeX\fonts\afm\adobe\utopia\putr8a.afm
WNCYB10=C:\Program Files\MiKTeX\fonts\afm\ams\cyrillic\wncyb10.afm
WNCYI10=C:\Program Files\MiKTeX\fonts\afm\ams\cyrillic\wncyi10.afm
WNCYR10=C:\Program Files\MiKTeX\fonts\afm\ams\cyrillic\wncyr10.afm
WNCYSC10=C:\Program Files\MiKTeX\fonts\afm\ams\cyrillic\wncysc10.afm
WNCYSS10=C:\Program Files\MiKTeX\fonts\afm\ams\cyrillic\wncyss10.afm
ZapfChancery-MediumItalic=C:\Program Files\MiKTeX\fonts\afm\adobe\zapfchan\pzcmi8a.afm
ZapfDingbats=C:\Program Files\MiKTeX\fonts\afm\adobe\zapfding\pzdr.afm
.
FontFamily
AMS=WNCYB10,WNCYB10,WNCYI10,WNCYI10,WNCYR10,WNCYR10,WNCYSC10,WNCYSC10,WNCYSS10,WNCYSS10
Bitstream Charter=Bold Italic,CharterBT-BoldItalic,Bold,CharterBT-Bold,Italic,CharterBT-Italic,Normal,CharterBT-Roman
Century Schoolbook L=Bold Italic,CenturySchL-BoldItal,Bold,CenturySchL-Bold,Italic,CenturySchL-Ital,Roman,CenturySchL-Roma
Computer Modern=LCMSS8,LCMSS8,LCMSSB8,LCMSSB8,LCMSSI8,LCMSSI8,MB10,CMB10,MBSY10,CMBSY10,MBSY5,CMBSY5,MBSY7,CMBSY7,MBX10,CMBX10,MBX12,CMBX12,MBX5,CMBX5,MBX6,CMBX6,MBX7,CMBX7,MBX8,CMBX8,MBX9,CMBX9,MBXSL10,CMBXSL10,MBXTI10,CMBXTI10,MCSC10,CMCSC10,MDUNH\
10,CMDUNH10,MEX10,CMEX10,MFF10,CMFF10,MFI10,CMFI10,MFIB8,CMFIB8,MINCH,CMINCH,MITT10,CMITT10,MMI10,CMMI10,MMI12,CMMI12,MMI5,CMMI5,MMI6,CMMI6,MMI7,CMMI7,MMI8,CMMI8,MMI9,CMMI9,MMIB10,CMMIB10,MMIB5,CMMIB5,MMIB7,CMMIB7,MR10,CMR10,MR12,CMR12,MR17,CMR17,MR\
5,CMR5,MR6,CMR6,MR7,CMR7,MR8,CMR8,MR9,CMR9,MSL10,CMSL10,MSL12,CMSL12,MSL8,CMSL8,MSL9,CMSL9,MSLTT10,CMSLTT10,MSS10,CMSS10,MSS12,CMSS12,MSS17,CMSS17,MSS8,CMSS8,MSS9,CMSS9,MSSBX10,CMSSBX10,MSSDC10,CMSSDC10,MSSI10,CMSSI10,MSSI12,CMSSI12,MSSI17,CMSSI17,M\
SSI8,CMSSI8,MSSI9,CMSSI9,MSSQ8,CMSSQ8,MSSQI8,CMSSQI8,MSY10,CMSY10,MSY5,CMSY5,MSY6,CMSY6,MSY7,CMSY7,MSY8,CMSY8,MSY9,CMSY9,MTCSC10,CMTCSC10,MTEX10,CMTEX10,MTEX8,CMTEX8,MTEX9,CMTEX9,MTI10,CMTI10,MTI12,CMTI12,MTI7,CMTI7,MTI8,CMTI8,MTI9,CMTI9,MTT10,CMTT1\
0,MTT12,CMTT12,MTT8,CMTT8,MTT9,CMTT9,MU10,CMU10,MVTT10,CMVTT10
Courier=Bold Italic,Courier-BoldItalic,Bold,Courier-Bold,Italic,Courier-Italic,Regular,Courier
Dingbats=Regular,Dingbats
Euler=MSAM10,MSAM10,MSAM5,MSAM5,MSAM7,MSAM7,MSBM10,MSBM10,MSBM5,MSBM5,MSBM7,MSBM7,UEX10,EUEX10,UFB10,EUFB10,UFB5,EUFB5,UFB7,EUFB7,UFM10,EUFM10,UFM5,EUFM5,UFM7,EUFM7,URB10,EURB10,URB5,EURB5,URB7,EURB7,URM10,EURM10,URM5,EURM5,URM7,EURM7,USB10,EUSB10,U\
SB5,EUSB5,USB7,EUSB7,USM10,EUSM10,USM5,EUSM5,USM7,EUSM7
Hershey- Gothic- English=Medium,Hershey-Gothic-English
Hershey- Gothic- German=Medium,Hershey-Gothic-German
Hershey- Gothic- Italian=Medium,Hershey-Gothic-Italian
Hershey- Plain- Duplex=Medium,Hershey-Plain-Duplex
Hershey- Plain- Duplex- Italic=Medium,Hershey-Plain-Duplex-Italic
Hershey- Plain- Triplex=Medium,Hershey-Plain-Triplex
Hershey- Plain- Triplex- Italic=Medium,Hershey-Plain-Triplex-Italic
Hershey- Script- Complex=Medium,Hershey-Script-Complex
Hershey- Script- Simplex=Medium,Hershey-Script-Simplex
Kevin=Medium),Calligraphic-Hiragana,Medium),Calligraphic-Katakana
La Te X=ASY10,LASY10,ASY5,LASY5,ASY6,LASY6,ASY7,LASY7,ASY8,LASY8,ASY9,LASY9,ASYB10,LASYB10,CIRCLE10,LCIRCLE10,CIRCLEW10,LCIRCLEW10,INE10,LINE10,INEW10,LINEW10
LOGO10=Medium,LOGO10
LOGO8=Medium,LOGO8
LOGO9=Medium,LOGO9
LOGOBF10=Bold,LOGOBF10
LOGOD10=DemiBold,LOGOD10
LOGOSL10=Medium,LOGOSL10
LOGOSL8=Medium,LOGOSL8
LOGOSL9=Medium,LOGOSL9
manfnt=Medium,manfnt
Math1 Mono)readonly=- Bold)readonly,Math1Mono-Bold,Normal)readonly,Math1Mono
Math1)readonly=- Bold)readonly,Math1-Bold,Normal)readonly,Math1
Math2 Mono)readonly=- Bold)readonly,Math2Mono-Bold,Normal)readonly,Math2Mono
Math2)readonly=- Bold)readonly,Math2-Bold,Normal)readonly,Math2
Math3 Mono)readonly=- Bold)readonly,Math3Mono-Bold,Normal)readonly,Math3Mono
Math3)readonly=- Bold)readonly,Math3-Bold,Normal)readonly,Math3
Math4 Mono)readonly=- Bold)readonly,Math4Mono-Bold,Normal)readonly,Math4Mono
Math4)readonly=- Bold)readonly,Math4-Bold,Normal)readonly,Math4
Math5 Mono)readonly=- Bold)readonly,Math5Mono-Bold,Normal)readonly,Math5Mono
Math5)readonly=- Bold)readonly,Math5-Bold,Normal)readonly,Math5
New Millenium Schlbk=- Bold Italic SH,NewMilleniumSchlbk-BoldItalicSH
Nimbus Mono L=Bold Oblique,NimbusMonL-BoldObli,Bold,NimbusMonL-Bold,Regular Oblique,NimbusMonL-ReguObli,Regular,NimbusMonL-Regu
Nimbus Roman No9 L=Medium Italic,NimbusRomNo9L-MediItal,Medium,NimbusRomNo9L-Medi,Regular Italic,NimbusRomNo9L-ReguItal,Regular,NimbusRomNo9L-Regu
Nimbus Roman No9L- Regular=L Regular,NimbusRomanNo9L-Regular
Nimbus Sans L=Bold Condensed Italic,NimbusSanL-BoldCondItal,Bold Condensed,NimbusSanL-BoldCond,Bold Italic,NimbusSanL-BoldItal,Bold,NimbusSanL-Bold,Regular Condensed Italic,NimbusSanL-ReguCondItal,Regular Condensed,NimbusSanL-ReguCond,Regular Italic\
,NimbusSanL-ReguItal,Regular,NimbusSanL-Regu
Nimbus Sans L- Regular=Regular,NimbusSansL-Regular
Omega Dingbats=Medium,OmegaDingbats
Omega Sans Tifinagh=Medium,OmegaSansTifinagh
Omega Serif Arabic One=- Bold,OmegaSerifArabicOne-Bold,Medium,OmegaSerifArabicOne
Omega Serif Arabic Three=- Bold,OmegaSerifArabicThree-Bold,Medium,OmegaSerifArabicThree
Omega Serif Arabic Two=- Bold,OmegaSerifArabicTwo-Bold,Medium,OmegaSerifArabicTwo
Omega Serif Armenian=Medium,OmegaSerifArmenian
Omega Serif Common=- Bold Italic,OmegaSerifCommon-BoldItalic,- Bold,OmegaSerifCommon-Bold,- Italic,OmegaSerifCommon-Italic,Medium,OmegaSerifCommon
Omega Serif Cyrillic=- Bold,OmegaSerifCyrillic-Bold,- Italic,OmegaSerifCyrillic-Italic,Medium,OmegaSerifCyrillic
Omega Serif Cyrillic Extended=Medium,OmegaSerifCyrillicExtended
Omega Serif Greek=- Bold Italic,OmegaSerifGreek-BoldItalic,- Bold,OmegaSerifGreek-Bold,- Italic,OmegaSerifGreek-Italic,Medium,OmegaSerifGreek
Omega Serif Hebrew=Medium,OmegaSerifHebrew
Omega Serif IPA=Medium,OmegaSerifIPA
Omega Serif Latin=- Bold Italic,OmegaSerifLatin-BoldItalic,- Bold,OmegaSerifLatin-Bold,- Italic,OmegaSerifLatin-Italic,Medium,OmegaSerifLatin
Omega Serif Tifinagh=Medium,OmegaSerifTifinagh
Shareware=Medium),Shareware-Cyrillic-Italic,Medium),Shareware-Cyrillic-Regular
Standard Symbols L=Regular,StandardSymL
Swiss 721=Bold Italic,Swiss721BT-BoldItalic,Bold,Swiss721BT-Bold,Italic,Swiss721BT-Italic
URW=Regular),URWAntiquaT-RegularCondensed,Regular),URWGroteskT-Bold
URW Antiqua T=Regular Condensed,URWAntiquaT-RegularCondensed
URW Bookman L=Demi Bold Italic,URWBookmanL-DemiBoldItal,Demi Bold,URWBookmanL-DemiBold,Light Italic,URWBookmanL-LighItal,Light,URWBookmanL-Ligh
URW Chancery L=Medium Italic,URWChanceryL-MediItal
URW Gothic L=Book Oblique,URWGothicL-BookObli,Book,URWGothicL-Book,Demi Oblique,URWGothicL-DemiObli,Demi,URWGothicL-Demi
URW Grotesk T=Bold,URWGroteskT-Bold
URW Palladio L=Bold Italic,URWPalladioL-BoldItal,Bold,URWPalladioL-Bold,Italic,URWPalladioL-Ital,Roman,URWPalladioL-Roma
Utopia=Bold Italic,Utopia-BoldItalic,Bold,Utopia-Bold,Italic,Utopia-Italic,Regular,Utopia-Regular
.
FontOutline
Calligraphic-Hiragana=c:\localt~1\gs\fonts\fhirw.gsf
Calligraphic-Katakana=c:\localt~1\gs\fonts\fkarw.gsf
CenturySchL-Bold=c:\localt~1\gs\fonts\c059016l.pfb
CenturySchL-Bold=C:\Program Files\MiKTeX\fonts\type1\urw\ncntrsbk\uncb8a.pfb
CenturySchL-BoldItal=c:\localt~1\gs\fonts\c059036l.pfb
CenturySchL-BoldItal=C:\Program Files\MiKTeX\fonts\type1\urw\ncntrsbk\uncbi8a.pfb
CenturySchL-Ital=c:\localt~1\gs\fonts\c059033l.pfb
CenturySchL-Ital=C:\Program Files\MiKTeX\fonts\type1\urw\ncntrsbk\uncri8a.pfb
CenturySchL-Roma=c:\localt~1\gs\fonts\c059013l.pfb
CenturySchL-Roma=C:\Program Files\MiKTeX\fonts\type1\urw\ncntrsbk\uncr8a.pfb
CharterBT-Bold=C:\LocalTeXMF\fonts\type1\Wolfram\c0632bt_.pfa
CharterBT-Bold=c:\localt~1\gs\fonts\bchb.pfa
CharterBT-BoldItalic=C:\LocalTeXMF\fonts\type1\Wolfram\c0633bt_.pfa
CharterBT-BoldItalic=c:\localt~1\gs\fonts\bchbi.pfa
CharterBT-Italic=C:\LocalTeXMF\fonts\type1\Wolfram\c0649bt_.pfa
CharterBT-Italic=c:\localt~1\gs\fonts\bchri.pfa
CharterBT-Roman=C:\LocalTeXMF\fonts\type1\Wolfram\c0648bt_.pfa
CharterBT-Roman=c:\localt~1\gs\fonts\bchr.pfa
CMB10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmb10.pfb
CMBSY10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmbsy10.pfb
CMBSY5=C:\Program Files\MiKTeX\fonts\type1\bluesky\cmextra\cmbsy5.pfb
CMBSY7=C:\Program Files\MiKTeX\fonts\type1\bluesky\cmextra\cmbsy7.pfb
CMBX10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmbx10.pfb
CMBX12=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmbx12.pfb
CMBX5=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmbx5.pfb
CMBX6=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmbx6.pfb
CMBX7=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmbx7.pfb
CMBX8=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmbx8.pfb
CMBX9=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmbx9.pfb
CMBXSL10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmbxsl10.pfb
CMBXTI10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmbxti10.pfb
CMCSC10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmcsc10.pfb
CMDUNH10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmdunh10.pfb
CMEX10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmex10.pfb
CMFF10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmff10.pfb
CMFI10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmfi10.pfb
CMFIB8=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmfib8.pfb
CMINCH=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cminch.pfb
CMITT10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmitt10.pfb
CMMI10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmmi10.pfb
CMMI12=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmmi12.pfb
CMMI5=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmmi5.pfb
CMMI6=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmmi6.pfb
CMMI7=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmmi7.pfb
CMMI8=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmmi8.pfb
CMMI9=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmmi9.pfb
CMMIB10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmmib10.pfb
CMMIB5=C:\Program Files\MiKTeX\fonts\type1\bluesky\cmextra\cmmib5.pfb
CMMIB7=C:\Program Files\MiKTeX\fonts\type1\bluesky\cmextra\cmmib7.pfb
CMR10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmr10.pfb
CMR12=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmr12.pfb
CMR17=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmr17.pfb
CMR5=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmr5.pfb
CMR6=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmr6.pfb
CMR7=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmr7.pfb
CMR8=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmr8.pfb
CMR9=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmr9.pfb
CMSL10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmsl10.pfb
CMSL12=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmsl12.pfb
CMSL8=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmsl8.pfb
CMSL9=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmsl9.pfb
CMSLTT10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmsltt10.pfb
CMSS10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmss10.pfb
CMSS12=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmss12.pfb
CMSS17=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmss17.pfb
CMSS8=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmss8.pfb
CMSS9=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmss9.pfb
CMSSBX10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmssbx10.pfb
CMSSDC10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmssdc10.pfb
CMSSI10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmssi10.pfb
CMSSI12=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmssi12.pfb
CMSSI17=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmssi17.pfb
CMSSI8=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmssi8.pfb
CMSSI9=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmssi9.pfb
CMSSQ8=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmssq8.pfb
CMSSQI8=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmssqi8.pfb
CMSY10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmsy10.pfb
CMSY5=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmsy5.pfb
CMSY6=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmsy6.pfb
CMSY7=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmsy7.pfb
CMSY8=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmsy8.pfb
CMSY9=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmsy9.pfb
CMTCSC10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmtcsc10.pfb
CMTEX10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmtex10.pfb
CMTEX8=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmtex8.pfb
CMTEX9=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmtex9.pfb
CMTI10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmti10.pfb
CMTI12=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmti12.pfb
CMTI7=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmti7.pfb
CMTI8=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmti8.pfb
CMTI9=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmti9.pfb
CMTT10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmtt10.pfb
CMTT12=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmtt12.pfb
CMTT8=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmtt8.pfb
CMTT9=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmtt9.pfb
CMU10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmu10.pfb
CMVTT10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\cmvtt10.pfb
Courier=C:\LocalTeXMF\fonts\type1\Wolfram\cour.pfa
Courier=C:\Program Files\MiKTeX\fonts\type1\adobe\courier\pcrr8a.pfb
Courier-Bold=C:\LocalTeXMF\fonts\type1\Wolfram\courb.pfa
Courier-Bold=C:\Program Files\MiKTeX\fonts\type1\adobe\courier\pcrb8a.pfb
Courier-BoldItalic=C:\LocalTeXMF\fonts\type1\Wolfram\courbi.pfa
Courier-BoldItalic=C:\Program Files\MiKTeX\fonts\type1\adobe\courier\pcrbi8a.pfb
Courier-BoldItalic=C:\Program Files\MiKTeX\fonts\type1\adobe\courier\pcrbo8a.pfb
Courier-Italic=C:\LocalTeXMF\fonts\type1\Wolfram\couri.pfa
Courier-Italic=C:\Program Files\MiKTeX\fonts\type1\adobe\courier\pcri8a.pfb
Courier-Italic=C:\Program Files\MiKTeX\fonts\type1\adobe\courier\pcrro8a.pfb
Dingbats=c:\localt~1\gs\fonts\d050000l.pfb
Dingbats=C:\Program Files\MiKTeX\fonts\type1\urw\zapfding\uzdr.pfb
EUEX10=C:\Program Files\MiKTeX\fonts\type1\bluesky\euler\euex10.pfb
EUFB10=C:\Program Files\MiKTeX\fonts\type1\bluesky\euler\eufb10.pfb
EUFB5=C:\Program Files\MiKTeX\fonts\type1\bluesky\euler\eufb5.pfb
EUFB7=C:\Program Files\MiKTeX\fonts\type1\bluesky\euler\eufb7.pfb
EUFM10=C:\Program Files\MiKTeX\fonts\type1\bluesky\euler\eufm10.pfb
EUFM5=C:\Program Files\MiKTeX\fonts\type1\bluesky\euler\eufm5.pfb
EUFM7=C:\Program Files\MiKTeX\fonts\type1\bluesky\euler\eufm7.pfb
EURB10=C:\Program Files\MiKTeX\fonts\type1\bluesky\euler\eurb10.pfb
EURB5=C:\Program Files\MiKTeX\fonts\type1\bluesky\euler\eurb5.pfb
EURB7=C:\Program Files\MiKTeX\fonts\type1\bluesky\euler\eurb7.pfb
EURM10=C:\Program Files\MiKTeX\fonts\type1\bluesky\euler\eurm10.pfb
EURM5=C:\Program Files\MiKTeX\fonts\type1\bluesky\euler\eurm5.pfb
EURM7=C:\Program Files\MiKTeX\fonts\type1\bluesky\euler\eurm7.pfb
EUSB10=C:\Program Files\MiKTeX\fonts\type1\bluesky\euler\eusb10.pfb
EUSB5=C:\Program Files\MiKTeX\fonts\type1\bluesky\euler\eusb5.pfb
EUSB7=C:\Program Files\MiKTeX\fonts\type1\bluesky\euler\eusb7.pfb
EUSM10=C:\Program Files\MiKTeX\fonts\type1\bluesky\euler\eusm10.pfb
EUSM5=C:\Program Files\MiKTeX\fonts\type1\bluesky\euler\eusm5.pfb
EUSM7=C:\Program Files\MiKTeX\fonts\type1\bluesky\euler\eusm7.pfb
Hershey-Gothic-English=c:\localt~1\gs\fonts\hrger.pfa
Hershey-Gothic-German=c:\localt~1\gs\fonts\hrgrr.pfa
Hershey-Gothic-Italian=c:\localt~1\gs\fonts\hritr.pfa
Hershey-Plain-Duplex=c:\localt~1\gs\fonts\hrpld.pfa
Hershey-Plain-Duplex-Italic=c:\localt~1\gs\fonts\hrpldi.pfa
Hershey-Plain-Triplex=c:\localt~1\gs\fonts\hrplt.pfa
Hershey-Plain-Triplex-Italic=c:\localt~1\gs\fonts\hrplti.pfa
Hershey-Script-Complex=c:\localt~1\gs\fonts\hrscc.pfa
Hershey-Script-Simplex=c:\localt~1\gs\fonts\hrscs.pfa
LASY10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\lasy10.pfb
LASY5=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\lasy5.pfb
LASY6=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\lasy6.pfb
LASY7=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\lasy7.pfb
LASY8=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\lasy8.pfb
LASY9=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\lasy9.pfb
LASYB10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\lasyb10.pfb
LCIRCLE10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\lcircle1.pfb
LCIRCLEW10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\lcirclew.pfb
LCMSS8=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\lcmss8.pfb
LCMSSB8=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\lcmssb8.pfb
LCMSSI8=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\lcmssi8.pfb
LINE10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\line10.pfb
LINEW10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cm\linew10.pfb
LOGO10=C:\Program Files\MiKTeX\fonts\type1\hoekwater\mflogo\logo10.pfb
LOGO8=C:\Program Files\MiKTeX\fonts\type1\hoekwater\mflogo\logo8.pfb
LOGO9=C:\Program Files\MiKTeX\fonts\type1\hoekwater\mflogo\logo9.pfb
LOGOBF10=C:\Program Files\MiKTeX\fonts\type1\hoekwater\mflogo\logobf10.pfb
LOGOD10=C:\Program Files\MiKTeX\fonts\type1\hoekwater\mflogo\logod10.pfb
LOGOSL10=C:\Program Files\MiKTeX\fonts\type1\hoekwater\mflogo\logosl10.pfb
LOGOSL8=C:\Program Files\MiKTeX\fonts\type1\hoekwater\mflogo\logosl8.pfb
LOGOSL9=C:\Program Files\MiKTeX\fonts\type1\hoekwater\mflogo\logosl9.pfb
manfnt=C:\Program Files\MiKTeX\fonts\type1\hoekwater\mflogo\manfnt.pfb
manfnt=C:\Program Files\MiKTeX\fonts\type1\hoekwater\misc\manfnt.pfb
Math1=C:\LocalTeXMF\fonts\type1\Wolfram\Math1.pfa
Math1=C:\LocalTeXMF\fonts\type1\Wolfram\Math1.pfb
Math1-Bold=C:\LocalTeXMF\fonts\type1\Wolfram\Math1-Bold.pfa
Math1-Bold=C:\LocalTeXMF\fonts\type1\Wolfram\Math1-Bold.pfb
Math1Mono=C:\LocalTeXMF\fonts\type1\Wolfram\Math1Mono.pfa
Math1Mono=C:\LocalTeXMF\fonts\type1\Wolfram\Math1Mono.pfb
Math1Mono-Bold=C:\LocalTeXMF\fonts\type1\Wolfram\Math1Mono-Bold.pfa
Math1Mono-Bold=C:\LocalTeXMF\fonts\type1\Wolfram\Math1Mono-Bold.pfb
Math2=C:\LocalTeXMF\fonts\type1\Wolfram\Math2.pfa
Math2=C:\LocalTeXMF\fonts\type1\Wolfram\Math2.pfb
Math2-Bold=C:\LocalTeXMF\fonts\type1\Wolfram\Math2-Bold.pfa
Math2-Bold=C:\LocalTeXMF\fonts\type1\Wolfram\Math2-Bold.pfb
Math2Mono=C:\LocalTeXMF\fonts\type1\Wolfram\Math2Mono.pfa
Math2Mono=C:\LocalTeXMF\fonts\type1\Wolfram\Math2Mono.pfb
Math2Mono-Bold=C:\LocalTeXMF\fonts\type1\Wolfram\Math2Mono-Bold.pfa
Math2Mono-Bold=C:\LocalTeXMF\fonts\type1\Wolfram\Math2Mono-Bold.pfb
Math3=C:\LocalTeXMF\fonts\type1\Wolfram\Math3.pfa
Math3=C:\LocalTeXMF\fonts\type1\Wolfram\Math3.pfb
Math3-Bold=C:\LocalTeXMF\fonts\type1\Wolfram\Math3-Bold.pfa
Math3-Bold=C:\LocalTeXMF\fonts\type1\Wolfram\Math3-Bold.pfb
Math3Mono=C:\LocalTeXMF\fonts\type1\Wolfram\Math3Mono.pfa
Math3Mono=C:\LocalTeXMF\fonts\type1\Wolfram\Math3Mono.pfb
Math3Mono-Bold=C:\LocalTeXMF\fonts\type1\Wolfram\Math3Mono-Bold.pfa
Math3Mono-Bold=C:\LocalTeXMF\fonts\type1\Wolfram\Math3Mono-Bold.pfb
Math4=C:\LocalTeXMF\fonts\type1\Wolfram\Math4.pfa
Math4=C:\LocalTeXMF\fonts\type1\Wolfram\Math4.pfb
Math4-Bold=C:\LocalTeXMF\fonts\type1\Wolfram\Math4-Bold.pfa
Math4-Bold=C:\LocalTeXMF\fonts\type1\Wolfram\Math4-Bold.pfb
Math4Mono=C:\LocalTeXMF\fonts\type1\Wolfram\Math4Mono.pfa
Math4Mono=C:\LocalTeXMF\fonts\type1\Wolfram\Math4Mono.pfb
Math4Mono-Bold=C:\LocalTeXMF\fonts\type1\Wolfram\Math4Mono-Bold.pfa
Math4Mono-Bold=C:\LocalTeXMF\fonts\type1\Wolfram\Math4Mono-Bold.pfb
Math5=C:\LocalTeXMF\fonts\type1\Wolfram\Math5.pfa
Math5=C:\LocalTeXMF\fonts\type1\Wolfram\Math5.pfb
Math5-Bold=C:\LocalTeXMF\fonts\type1\Wolfram\Math5-Bold.pfa
Math5-Bold=C:\LocalTeXMF\fonts\type1\Wolfram\Math5-Bold.pfb
Math5Mono=C:\LocalTeXMF\fonts\type1\Wolfram\Math5Mono.pfa
Math5Mono=C:\LocalTeXMF\fonts\type1\Wolfram\Math5Mono.pfb
Math5Mono-Bold=C:\LocalTeXMF\fonts\type1\Wolfram\Math5Mono-Bold.pfa
Math5Mono-Bold=C:\LocalTeXMF\fonts\type1\Wolfram\Math5Mono-Bold.pfb
MSAM10=C:\Program Files\MiKTeX\fonts\type1\bluesky\symbols\msam10.pfb
MSAM5=C:\Program Files\MiKTeX\fonts\type1\bluesky\symbols\msam5.pfb
MSAM7=C:\Program Files\MiKTeX\fonts\type1\bluesky\symbols\msam7.pfb
MSBM10=C:\Program Files\MiKTeX\fonts\type1\bluesky\symbols\msbm10.pfb
MSBM5=C:\Program Files\MiKTeX\fonts\type1\bluesky\symbols\msbm5.pfb
MSBM7=C:\Program Files\MiKTeX\fonts\type1\bluesky\symbols\msbm7.pfb
NewMilleniumSchlbk-BoldItalicSH=c:\localt~1\gs\fonts\nemsbis_.pfb
NimbusMonL-Bold=c:\localt~1\gs\fonts\n022004l.pfb
NimbusMonL-Bold=C:\Program Files\MiKTeX\fonts\type1\urw\courier\ucrb8a.pfb
NimbusMonL-BoldObli=c:\localt~1\gs\fonts\n022024l.pfb
NimbusMonL-BoldObli=C:\Program Files\MiKTeX\fonts\type1\urw\courier\ucrbo8a.pfb
NimbusMonL-Regu=c:\localt~1\gs\fonts\n022003l.pfb
NimbusMonL-Regu=C:\Program Files\MiKTeX\fonts\type1\urw\courier\ucrr8a.pfb
NimbusMonL-ReguObli=c:\localt~1\gs\fonts\n022023l.pfb
NimbusMonL-ReguObli=C:\Program Files\MiKTeX\fonts\type1\urw\courier\ucrro8a.pfb
NimbusRomanNo9L-Regular=C:\Program Files\MiKTeX\fonts\type1\urw\unm\unmr8a.pfb
NimbusRomNo9L-Medi=c:\localt~1\gs\fonts\n021004l.pfb
NimbusRomNo9L-Medi=C:\Program Files\MiKTeX\fonts\type1\urw\times\utmb8a.pfb
NimbusRomNo9L-MediItal=c:\localt~1\gs\fonts\n021024l.pfb
NimbusRomNo9L-MediItal=C:\Program Files\MiKTeX\fonts\type1\urw\times\utmbi8a.pfb
NimbusRomNo9L-Regu=c:\localt~1\gs\fonts\n021003l.pfb
NimbusRomNo9L-Regu=C:\Program Files\MiKTeX\fonts\type1\urw\times\utmr8a.pfb
NimbusRomNo9L-ReguItal=c:\localt~1\gs\fonts\n021023l.pfb
NimbusRomNo9L-ReguItal=C:\Program Files\MiKTeX\fonts\type1\urw\times\utmri8a.pfb
NimbusSanL-Bold=c:\localt~1\gs\fonts\n019004l.pfb
NimbusSanL-Bold=C:\Program Files\MiKTeX\fonts\type1\urw\helvetic\uhvb8a.pfb
NimbusSanL-BoldCond=c:\localt~1\gs\fonts\n019044l.pfb
NimbusSanL-BoldCond=C:\Program Files\MiKTeX\fonts\type1\urw\helvetic\uhvb8ac.pfb
NimbusSanL-BoldCond=C:\Program Files\MiKTeX\fonts\type1\urw\helvetic\uhvbrc8a.pfb
NimbusSanL-BoldCondItal=c:\localt~1\gs\fonts\n019064l.pfb
NimbusSanL-BoldCondItal=C:\Program Files\MiKTeX\fonts\type1\urw\helvetic\uhvbo8ac.pfb
NimbusSanL-BoldCondItal=C:\Program Files\MiKTeX\fonts\type1\urw\helvetic\uhvboc8a.pfb
NimbusSanL-BoldItal=c:\localt~1\gs\fonts\n019024l.pfb
NimbusSanL-BoldItal=C:\Program Files\MiKTeX\fonts\type1\urw\helvetic\uhvbo8a.pfb
NimbusSanL-Regu=c:\localt~1\gs\fonts\n019003l.pfb
NimbusSanL-Regu=C:\Program Files\MiKTeX\fonts\type1\urw\helvetic\uhvr8a.pfb
NimbusSanL-ReguCond=c:\localt~1\gs\fonts\n019043l.pfb
NimbusSanL-ReguCond=C:\Program Files\MiKTeX\fonts\type1\urw\helvetic\uhvr8ac.pfb
NimbusSanL-ReguCond=C:\Program Files\MiKTeX\fonts\type1\urw\helvetic\uhvrrc8a.pfb
NimbusSanL-ReguCondItal=c:\localt~1\gs\fonts\n019063l.pfb
NimbusSanL-ReguCondItal=C:\Program Files\MiKTeX\fonts\type1\urw\helvetic\uhvro8ac.pfb
NimbusSanL-ReguCondItal=C:\Program Files\MiKTeX\fonts\type1\urw\helvetic\uhvroc8a.pfb
NimbusSanL-ReguItal=c:\localt~1\gs\fonts\n019023l.pfb
NimbusSanL-ReguItal=C:\Program Files\MiKTeX\fonts\type1\urw\helvetic\uhvro8a.pfb
NimbusSansL-Regular=C:\Program Files\MiKTeX\fonts\type1\urw\unms\unmrs8a.pfb
OmegaDingbats=C:\Program Files\MiKTeX\fonts\type1\public\omega\omding.pfb
OmegaSansTifinagh=C:\Program Files\MiKTeX\fonts\type1\public\omega\omssti.pfb
OmegaSerifArabicOne=C:\Program Files\MiKTeX\fonts\type1\public\omega\omsea1.pfb
OmegaSerifArabicOne-Bold=C:\Program Files\MiKTeX\fonts\type1\public\omega\omsea1b.pfb
OmegaSerifArabicThree=C:\Program Files\MiKTeX\fonts\type1\public\omega\omsea3.pfb
OmegaSerifArabicThree-Bold=C:\Program Files\MiKTeX\fonts\type1\public\omega\omsea3b.pfb
OmegaSerifArabicTwo=C:\Program Files\MiKTeX\fonts\type1\public\omega\omsea2.pfb
OmegaSerifArabicTwo-Bold=C:\Program Files\MiKTeX\fonts\type1\public\omega\omsea2b.pfb
OmegaSerifArmenian=C:\Program Files\MiKTeX\fonts\type1\public\omega\omseha.pfb
OmegaSerifCommon=C:\Program Files\MiKTeX\fonts\type1\public\omega\omseco.pfb
OmegaSerifCommon-Bold=C:\Program Files\MiKTeX\fonts\type1\public\omega\omsecob.pfb
OmegaSerifCommon-BoldItalic=C:\Program Files\MiKTeX\fonts\type1\public\omega\omsecobi.pfb
OmegaSerifCommon-Italic=C:\Program Files\MiKTeX\fonts\type1\public\omega\omsecoi.pfb
OmegaSerifCyrillic=C:\Program Files\MiKTeX\fonts\type1\public\omega\omsecy.pfb
OmegaSerifCyrillic-Bold=C:\Program Files\MiKTeX\fonts\type1\public\omega\omsecyb.pfb
OmegaSerifCyrillic-Italic=C:\Program Files\MiKTeX\fonts\type1\public\omega\omsecyi.pfb
OmegaSerifCyrillicExtended=C:\Program Files\MiKTeX\fonts\type1\public\omega\omsecx.pfb
OmegaSerifGreek=C:\Program Files\MiKTeX\fonts\type1\public\omega\omsegr.pfb
OmegaSerifGreek-Bold=C:\Program Files\MiKTeX\fonts\type1\public\omega\omsegrb.pfb
OmegaSerifGreek-BoldItalic=C:\Program Files\MiKTeX\fonts\type1\public\omega\omsegrbi.pfb
OmegaSerifGreek-Italic=C:\Program Files\MiKTeX\fonts\type1\public\omega\omsegri.pfb
OmegaSerifHebrew=C:\Program Files\MiKTeX\fonts\type1\public\omega\omsehe.pfb
OmegaSerifIPA=C:\Program Files\MiKTeX\fonts\type1\public\omega\omseip.pfb
OmegaSerifLatin=C:\Program Files\MiKTeX\fonts\type1\public\omega\omsela.pfb
OmegaSerifLatin-Bold=C:\Program Files\MiKTeX\fonts\type1\public\omega\omselab.pfb
OmegaSerifLatin-BoldItalic=C:\Program Files\MiKTeX\fonts\type1\public\omega\omselabi.pfb
OmegaSerifLatin-Italic=C:\Program Files\MiKTeX\fonts\type1\public\omega\omselai.pfb
OmegaSerifTifinagh=C:\Program Files\MiKTeX\fonts\type1\public\omega\omseti.pfb
Shareware-Cyrillic-Italic=c:\localt~1\gs\fonts\fcyri.gsf
Shareware-Cyrillic-Regular=c:\localt~1\gs\fonts\fcyr.gsf
StandardSymL=c:\localt~1\gs\fonts\s050000l.pfb
StandardSymL=C:\Program Files\MiKTeX\fonts\type1\urw\symbol\usyr.pfb
Swiss721BT-Bold=C:\LocalTeXMF\fonts\type1\Wolfram\Swiss721BT-Bold.pfa
Swiss721BT-BoldItalic=C:\LocalTeXMF\fonts\type1\Wolfram\Swiss721BT-BoldItalic.pfa
Swiss721BT-Italic=C:\LocalTeXMF\fonts\type1\Wolfram\Swiss721BT-Italic.pfa
Swiss721BT-Roman=C:\LocalTeXMF\fonts\type1\Wolfram\Swiss721BT-Roman.pfa
URWAntiquaT-RegularCondensed=c:\localt~1\gs\fonts\u003043t.gsf
URWAntiquaT-RegularCondensed=C:\Program Files\MiKTeX\fonts\type1\urw\uaq\uaqr8ac.pfb
URWBookmanL-DemiBold=c:\localt~1\gs\fonts\b018015l.pfb
URWBookmanL-DemiBold=C:\Program Files\MiKTeX\fonts\type1\urw\bookman\ubkd8a.pfb
URWBookmanL-DemiBoldItal=c:\localt~1\gs\fonts\b018035l.pfb
URWBookmanL-DemiBoldItal=C:\Program Files\MiKTeX\fonts\type1\urw\bookman\ubkdi8a.pfb
URWBookmanL-Ligh=c:\localt~1\gs\fonts\b018012l.pfb
URWBookmanL-Ligh=C:\Program Files\MiKTeX\fonts\type1\urw\bookman\ubkl8a.pfb
URWBookmanL-LighItal=c:\localt~1\gs\fonts\b018032l.pfb
URWBookmanL-LighItal=C:\Program Files\MiKTeX\fonts\type1\urw\bookman\ubkli8a.pfb
URWChanceryL-MediItal=c:\localt~1\gs\fonts\z003034l.pfb
URWChanceryL-MediItal=C:\Program Files\MiKTeX\fonts\type1\urw\zapfchan\uzcmi8a.pfb
URWGothicL-Book=c:\localt~1\gs\fonts\a010013l.pfb
URWGothicL-Book=C:\Program Files\MiKTeX\fonts\type1\urw\avantgar\uagk8a.pfb
URWGothicL-BookObli=c:\localt~1\gs\fonts\a010033l.pfb
URWGothicL-BookObli=C:\Program Files\MiKTeX\fonts\type1\urw\avantgar\uagko8a.pfb
URWGothicL-Demi=c:\localt~1\gs\fonts\a010015l.pfb
URWGothicL-Demi=C:\Program Files\MiKTeX\fonts\type1\urw\avantgar\uagd8a.pfb
URWGothicL-DemiObli=c:\localt~1\gs\fonts\a010035l.pfb
URWGothicL-DemiObli=C:\Program Files\MiKTeX\fonts\type1\urw\avantgar\uagdo8a.pfb
URWGroteskT-Bold=c:\localt~1\gs\fonts\u004006t.gsf
URWGroteskT-Bold=C:\Program Files\MiKTeX\fonts\type1\urw\ugq\ugqb8a.pfb
URWPalladioL-Bold=c:\localt~1\gs\fonts\p052004l.pfb
URWPalladioL-Bold=C:\Program Files\MiKTeX\fonts\type1\urw\palatino\uplb8a.pfb
URWPalladioL-BoldItal=c:\localt~1\gs\fonts\p052024l.pfb
URWPalladioL-BoldItal=C:\Program Files\MiKTeX\fonts\type1\urw\palatino\uplbi8a.pfb
URWPalladioL-Ital=c:\localt~1\gs\fonts\p052023l.pfb
URWPalladioL-Ital=C:\Program Files\MiKTeX\fonts\type1\urw\palatino\uplri8a.pfb
URWPalladioL-Roma=c:\localt~1\gs\fonts\p052003l.pfb
URWPalladioL-Roma=C:\Program Files\MiKTeX\fonts\type1\urw\palatino\uplr8a.pfb
Utopia-Bold=C:\LocalTeXMF\fonts\type1\Wolfram\UTB_____.pfa
Utopia-Bold=c:\localt~1\gs\fonts\putb.pfa
Utopia-Bold=C:\Program Files\MiKTeX\fonts\type1\adobe\utopia\putb8a.pfb
Utopia-BoldItalic=C:\LocalTeXMF\fonts\type1\Wolfram\UTBI____.pfa
Utopia-BoldItalic=c:\localt~1\gs\fonts\putbi.pfa
Utopia-BoldItalic=C:\Program Files\MiKTeX\fonts\type1\adobe\utopia\putbi8a.pfb
Utopia-Italic=C:\LocalTeXMF\fonts\type1\Wolfram\UTI_____.pfa
Utopia-Italic=c:\localt~1\gs\fonts\putri.pfa
Utopia-Italic=C:\Program Files\MiKTeX\fonts\type1\adobe\utopia\putri8a.pfb
Utopia-Regular=C:\LocalTeXMF\fonts\type1\Wolfram\UTRG____.pfa
Utopia-Regular=c:\localt~1\gs\fonts\putr.pfa
Utopia-Regular=C:\Program Files\MiKTeX\fonts\type1\adobe\utopia\putr8a.pfb
WNCYB10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cyrillic\wncyb10.pfb
WNCYI10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cyrillic\wncyi10.pfb
WNCYR10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cyrillic\wncyr10.pfb
WNCYSC10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cyrillic\wncysc10.pfb
WNCYSS10=C:\Program Files\MiKTeX\fonts\type1\bluesky\cyrillic\wncyss10.pfb
.
FontPFM
Dingbats=c:\localt~1\gs\fonts\d050000l.pfm
Dingbats=C:\Program Files\MiKTeX\fonts\type1\urw\zapfding\uzdr.pfm
Hiragana=c:\localt~1\gs\fonts\fhirw.pfm
Katakana=c:\localt~1\gs\fonts\fkarw.pfm
NewMilleniumSchlbk-BoldItalicSH=c:\localt~1\gs\fonts\nemsbis_.pfm
StandardSymL=c:\localt~1\gs\fonts\s050000l.pfm
StandardSymL=C:\Program Files\MiKTeX\fonts\type1\urw\symbol\usyr.pfm
URWAntiquaT-RegularCondensed=c:\localt~1\gs\fonts\u003043t.pfm
URWGroteskT-Bold=c:\localt~1\gs\fonts\u004006t.pfm
.
mkpsresPrivate
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\config.mga
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\config.mbn
NONRESOURCE=C:\Program Files\MiKTeX\dvips\urw\ucr.map
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gssetgs.bat
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\cdj690.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_dps.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\base\hps.pro
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\decrypt.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\stcolor.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\Fontmap.SGI
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\Fontmap.Sol
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\context.map
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\cbjc800.ppd
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\bakomaextra.map
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\dnj750m.upp
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\config.ot2
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\viewcmyk.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\config.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\lprsetup.sh
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\Fontmap.Ult
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\config.pdf
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\stc2s_h.upp
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\ncntrsbk\uncri8a.pfm
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\palatino\uplbi8a.pfm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\pfbtopfa
NONRESOURCE=C:\Program Files\MiKTeX\dvips\base\crop.pro
NONRESOURCE=C:\Program Files\MiKTeX\dvips\cspsfonts\config.cs
NONRESOURCE=C:\Program Files\MiKTeX\dvips\hoekwater\hoekwater.map
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\Fontmap.VMS
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\showpage.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\urw\uhv.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\config.qms
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\align.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_ttf.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\config.dfaxlo
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\pdf_ops.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\viewpbm.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\bluesky\bsr.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\ljfour.cfg
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ppath.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\lp386r2.bat
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\config.dvired
NONRESOURCE=C:\Program Files\MiKTeX\dvips\base\special.pro
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\unix-lpr.sh
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\winmaps.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gstt.bat
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\dvired.cfg
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\pdfwrite.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\urw\usy.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\ps2pk\ps2pk.map
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2epsi.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\viewps2a.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gsndt.bat
NONRESOURCE=c:\localt~1\gs\fonts\hrsyr.gsf
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\stc500p.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\stc600p.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\stc800p.upp
NONRESOURCE=C:\Program Files\MiKTeX\dvips\base\finclude.pro
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\config.uaq
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\config.ugq
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\zapfchan\uzcmi8a.pfm
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\ncntrsbk\uncr8a.pfm
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\palatino\uplb8a.pfm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2ascii.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\wftopfa.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\pcharstr.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\lpr2.bat
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\epson.cfg
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\wmakebat.bat
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\config.www
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\necp2x6.upp
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\config.xyp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\stc640p.upp
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\times\utmb8a.pfm
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\times\utmr8a.pfm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\dvipdf
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\config.bakoma
NONRESOURCE=C:\Program Files\MiKTeX\dvips\omega\omega.cfg
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\type1enc.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\fixmswrd.pl
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\markpath.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\prfont.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\uninfo.ps
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\avantgar\uagdo8a.pfm
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\lw35extra.mapfile
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\printafm
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\extra.map
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\stc_h.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\type1ops.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\viewpcx.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\stc2.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\font2c.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\pdfopt.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\config.ibmvga
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_wan_e.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\zeroline.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_l_m.xbm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_m_m.xbm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_s_m.xbm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_t_m.xbm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gsnup.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bjc610a0.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bjc610a1.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bjc610a2.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bjc610a3.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bjc610a4.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bjc610a5.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bjc610a6.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bjc610a7.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bjc610a8.upp
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\bookman\ubkdi8a.pfm
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\bookman\ubkli8a.pfm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\st640pg.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_dbt_e.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.hlc
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.hlh
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.hls
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\pf2afm.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.hlx
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bjc610b1.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bjc610b2.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bjc610b3.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bjc610b4.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bjc610b6.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bjc610b7.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bjc610b8.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\st640ih.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2pdf12
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2pdf13
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2pdf14
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\config.canonex
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\st640p.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bdftops
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\lp386.bat
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\palatino\uplri8a.pfm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2ps.bat
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\stc_l.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\addxchar.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_pdf_e.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2ps.cmd
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\avantgar\uagd8a.pfm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\stocht.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_mex_e.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\config.deskjet
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\wrfont.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\base\ehandler.ps
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\avantgar\uagko8a.pfm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\pdf2dsc
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\st640pl.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_lgo_e.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_lgx_e.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_mgl_e.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.ma1
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mb1
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mc1
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mm1
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mp1
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.ms1
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.ma2
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mb2
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mp2
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.ms2
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mb3
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mg4
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mg5
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mc6
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mc7
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mc8
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\qms.cfg
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2ai.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mza
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mbb
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.msb
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mwb
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mnc
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mzc
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mbd
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mcd
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mhd
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mvd
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mzd
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mbe
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mee
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mfe
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mme
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.moe
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mbf
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mcf
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mif
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mag
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mng
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mah
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mph
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mai
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mfi
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mii
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mni
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mbk
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mal
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mel
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mkl
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mpl
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mgm
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.msm
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mjn
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mnn
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mgo
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mho
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mio
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mjo
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mmo
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mnp
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mpp
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mgq
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mcr
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mgr
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mnr
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mur
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mcs
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mds
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mfs
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mgs
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mis
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mns
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mos
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.met
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mgt
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mnt
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mot
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mzt
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mcu
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mbv
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mhv
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mov
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mrw
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.msw
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mtw
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mox
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mgy
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.msy
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mty
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.mpz
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\impath.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\omega\omega.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.nnt
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\level1.ps
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\palatino\uplr8a.pfm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\cid2code.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\acrobat_kb_kb.mapfile
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\acrobat.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\bluesky\config.ams
NONRESOURCE=C:\Program Files\MiKTeX\dvips\bluesky\config.amz
NONRESOURCE=C:\Program Files\MiKTeX\dvips\bluesky\config.cmz
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2pdfwr
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\eps2eps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gst.bat
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\mirr.hd
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\lines.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2ascii
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.pbb
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.peb
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.pnb
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.psb
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.pad
NONRESOURCE=c:\localt~1\gs\fonts\hrsccb.gsf
NONRESOURCE=c:\localt~1\gs\fonts\hrscsb.gsf
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.pgm
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.pjn
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.pmn
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.pun
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.pop
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.pur
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.pgs
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.pst
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.put
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.pbv
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\config.ljfour
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\afmdiff.awk
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\avantgar\uagk8a.pfm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gsdj500
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_il1_e.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_il2_e.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_kanji.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_wl1_e.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_wl2_e.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_wl5_e.ps
NONRESOURCE=c:\localt~1\gs\fonts\fonts.scale
NONRESOURCE=c:\localt~1\gs\fonts\hrgerb.gsf
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\sysvlp.sh
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_ce_e.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\bluesky\psfonts.ams
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_cidcm.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\bluesky\psfonts.amz
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gslp.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\ma1.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\ma2.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mag.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mah.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mai.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mal.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\map.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\pad.map
NONRESOURCE=c:\localt~1\gs\fonts\hrpldbi.gsf
NONRESOURCE=c:\localt~1\gs\fonts\hrplrbo.gsf
NONRESOURCE=c:\localt~1\gs\fonts\hrplsbo.gsf
NONRESOURCE=c:\localt~1\gs\fonts\hrpltbi.gsf
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_rdlin.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\stcany_h.upp
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mb1.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mb2.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mb3.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mbb.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mbd.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mbe.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mbf.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mbk.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mbv.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\pbb.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\pbv.map
NONRESOURCE=c:\localt~1\gs\fonts\hrgerd.gsf
NONRESOURCE=C:\Program Files\MiKTeX\dvips\bluesky\psfonts.cm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\unprot.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\bluesky\psfonts.cmz
NONRESOURCE=C:\LocalTeXMF\dvips\duplex
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\helvetic\uhvbo8a.pfm
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mc1.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mc6.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mc7.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mc8.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mcd.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mcf.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mcr.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mcs.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mcu.map
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\pj-gs.sh
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ras1.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ras3.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ras4.upp
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.unc
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.uzc
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.uzd
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.uag
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.ubk
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.upl
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.unm
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.utm
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.uaq
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.ugq
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.ucr
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.uhv
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\config.usy
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\stc200_h.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_cidfn.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\canonex.cfg
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\deskjet.cfg
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mds.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\lw35extra_urw.mapfile
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mee.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mel.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\met.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\peb.map
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\font2c
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2pdf
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_ccfnt.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_mro_e.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\pdf2ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\pdfopt
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mfe.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mfi.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mfs.map
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2pdf12.bat
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2pdf13.bat
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2pdf14.bat
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_css_e.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_ksb_e.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_pfile.ps
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\bookman\ubkd8a.pfm
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\bookman\ubkl8a.pfm
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\lw35extra_kb_urw.mapfile
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mg4.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mg5.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mgm.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mgo.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mgq.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mgr.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mgs.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mgt.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mgy.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\pgm.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\pgs.map
NONRESOURCE=c:\localt~1\gs\fonts\hrpldb.gsf
NONRESOURCE=c:\localt~1\gs\fonts\hrplrb.gsf
NONRESOURCE=c:\localt~1\gs\fonts\hrplsb.gsf
NONRESOURCE=c:\localt~1\gs\fonts\hrpltb.gsf
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\pf2afm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ras8m.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_std_e.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\toshiba.cfg
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\config.toshiba
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\quit.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mhd.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mho.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mhv.map
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gsbj
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\helvetic\uhvb8a.pfm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_diskf.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\charter.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mif.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mii.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mio.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mis.map
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\cdj690ec.upp
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\courier\ucrbo8a.pfm
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\courier\ucrro8a.pfm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_setpd.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\pdf_draw.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\base\texps.pro
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mjn.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mjo.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\pjn.map
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gsdj
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mkl.map
NONRESOURCE=c:\localt~1\gs\fonts\hrscco.gsf
NONRESOURCE=c:\localt~1\gs\fonts\hrscso.gsf
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\stc.upp
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\config.dfaxhigh
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bj8.rpd
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\hlh.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\hls.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\hlx.map
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ras32.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_epsf.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_frsd.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_fform.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_sym_e.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ht_ccsto.ps
NONRESOURCE=c:\localt~1\gs\fonts\a010013l.pfm
NONRESOURCE=c:\localt~1\gs\fonts\a010015l.pfm
NONRESOURCE=c:\localt~1\gs\fonts\n021003l.pfm
NONRESOURCE=c:\localt~1\gs\fonts\n021004l.pfm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bdftops.bat
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mm1.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mme.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mmo.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\pmn.map
NONRESOURCE=c:\localt~1\gs\fonts\hrgero.gsf
NONRESOURCE=c:\localt~1\gs\fonts\hrgrrb.gsf
NONRESOURCE=C:\Program Files\MiKTeX\dvips\base\texc.pro
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bj8gc12f.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_lev2.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\dfaxhigh.cfg
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\acctest.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\errpage.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\pdf2dsc.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2ascii.bat
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2pdfxx.bat
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\stc600ih.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\stc800ih.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bdftops.cmd
NONRESOURCE=c:\localt~1\gs\fonts\n022003l.pfm
NONRESOURCE=c:\localt~1\gs\fonts\n022004l.pfm
NONRESOURCE=c:\localt~1\gs\fonts\p052003l.pfm
NONRESOURCE=c:\localt~1\gs\fonts\p052004l.pfm
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mnc.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mng.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mni.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mnn.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mnp.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mnr.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mns.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mnt.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\nnt.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\pnb.map
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ras24.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\image-qa.ps
NONRESOURCE=c:\localt~1\gs\fonts\a010033l.pfm
NONRESOURCE=c:\localt~1\gs\fonts\a010035l.pfm
NONRESOURCE=c:\localt~1\gs\fonts\n021023l.pfm
NONRESOURCE=c:\localt~1\gs\fonts\n021024l.pfm
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\moe.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mos.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mot.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mov.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mox.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\pop.map
NONRESOURCE=c:\localt~1\gs\fonts\hritrb.gsf
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bj8pa06n.upp
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\config.epson
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_cmdl.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\hlce.map
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_pdfwr.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\bluesky\config.cm
NONRESOURCE=c:\localt~1\gs\fonts\n022023l.pfm
NONRESOURCE=c:\localt~1\gs\fonts\n022024l.pfm
NONRESOURCE=c:\localt~1\gs\fonts\p052023l.pfm
NONRESOURCE=c:\localt~1\gs\fonts\p052024l.pfm
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mp1.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mp2.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mph.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mpl.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mpp.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mpz.map
NONRESOURCE=C:\LocalTeXMF\dvips\fontmap\Wolfram\wolfram.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\hlcf.map
NONRESOURCE=c:\localt~1\gs\fonts\uninstal.txt
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\bsr-interpolated.map
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bj8hg12f.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\jispaper.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2epsi
NONRESOURCE=c:\localt~1\gs\fonts\z003034l.pfm
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mrw.map
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2pdf12.cmd
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2pdf13.cmd
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2pdf14.cmd
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gslj
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gslp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gsdj500.bat
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\Fontmap.ATB
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\Fontmap.ATM
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_type1.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\eps2eps.bat
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\helvetic\uhvro8a.pfm
NONRESOURCE=C:\Program Files\MiKTeX\dvips\base\color.pro
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\ms1.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\ms2.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\msb.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\msm.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\msw.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\msy.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\psb.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\pst.map
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\stc2_h.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_l2img.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_cmap.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_btokn.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\packfile.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\eps2eps.cmd
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\pftogsf.bat
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mtw.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mty.map
NONRESOURCE=c:\localt~1\gs\fonts\hrplro.gsf
NONRESOURCE=c:\localt~1\gs\fonts\hrplso.gsf
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gsnd
NONRESOURCE=C:\Program Files\MiKTeX\dvips\base\resolution400.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\stc500ph.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\stc600pl.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\stc800pl.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\showchar.ps
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\courier\ucrb8a.pfm
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\courier\ucrr8a.pfm
NONRESOURCE=c:\localt~1\gs\fonts\b018012l.pfm
NONRESOURCE=c:\localt~1\gs\fonts\b018015l.pfm
NONRESOURCE=c:\localt~1\gs\fonts\n019003l.pfm
NONRESOURCE=c:\localt~1\gs\fonts\n019004l.pfm
NONRESOURCE=C:\Program Files\MiKTeX\dvips\urw\unc.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\urw\uzc.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mur.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\pun.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\pur.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\put.map
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\font2c.bat
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2pdf.bat
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\cx.cfg
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\pdf2ps.bat
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\pdfopt.bat
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psutils\md68_0.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\pfbtopfa.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\traceimg.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\omega\config.omega
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_l.xbm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_m.xbm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_s.xbm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_t.xbm
NONRESOURCE=c:\localt~1\gs\fonts\c059013l.pfm
NONRESOURCE=c:\localt~1\gs\fonts\c059016l.pfm
NONRESOURCE=C:\Program Files\MiKTeX\dvips\urw\uzd.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mvd.map
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bj8oh06n.upp
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psutils\md71_0.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\ibmvga.cfg
NONRESOURCE=c:\localt~1\gs\fonts\b018032l.pfm
NONRESOURCE=c:\localt~1\gs\fonts\b018035l.pfm
NONRESOURCE=c:\localt~1\gs\fonts\n019023l.pfm
NONRESOURCE=c:\localt~1\gs\fonts\n019024l.pfm
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\ncntrsbk\uncbi8a.pfm
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mwb.map
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\pf2afm.bat
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\updmap
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_dps1.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\font2pcl.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\hlcm.map
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_fonts.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gsbj.bat
NONRESOURCE=c:\localt~1\gs\fonts\c059033l.pfm
NONRESOURCE=c:\localt~1\gs\fonts\c059036l.pfm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\Fontmap.GS
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_dps2.ps
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\helvetic\uhvr8a.pfm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_init.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_trap.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\viewgif.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\hlcn.map
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\pdf_font.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\viewjpeg.ps
NONRESOURCE=c:\localt~1\gs\fonts\n019043l.pfm
NONRESOURCE=c:\localt~1\gs\fonts\n019044l.pfm
NONRESOURCE=C:\Program Files\MiKTeX\dvips\urw\uag.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\config.unms
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_res.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\stc1520h.upp
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\config.cx
NONRESOURCE=C:\Program Files\MiKTeX\dvips\base\tex.pro
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_dscp.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2ascii.cmd
NONRESOURCE=c:\localt~1\gs\fonts\fonts.dir
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\pdf_base.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gsdj.bat
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\config.cms
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mza.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mzc.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mzd.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\mzt.map
NONRESOURCE=c:\localt~1\gs\fonts\hrgrro.gsf
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_cff.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bj8pp12f.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bdftops.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\caption.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\traceop.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\pdf_main.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\cspsfonts\rawfonts.map
NONRESOURCE=c:\localt~1\gs\fonts\n019063l.pfm
NONRESOURCE=c:\localt~1\gs\fonts\n019064l.pfm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\wftopfa
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_agl.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\dnj750c.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\docie.ps
NONRESOURCE=c:\localt~1\gs\fonts\hritro.gsf
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\ncntrsbk\uncb8a.pfm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\pdf_sec.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_dpnxt.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_statd.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\landscap.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\viewmiff.ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\urw\ubk.map
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\pv.sh
NONRESOURCE=c:\localt~1\gs\fonts\hrgkc.gsf
NONRESOURCE=c:\localt~1\gs\fonts\hrgks.gsf
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\rollconv.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2epsi.bat
NONRESOURCE=C:\Program Files\MiKTeX\dvips\urw\upl.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\alt-rule.pro
NONRESOURCE=c:\localt~1\gs\fonts\hrplr.gsf
NONRESOURCE=c:\localt~1\gs\fonts\hrpls.gsf
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2epsi.cmd
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\hlct.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\hlst.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\urw\utm.map
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\times\utmbi8a.pfm
NONRESOURCE=C:\Program Files\MiKTeX\fonts\type1\urw\times\utmri8a.pfm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\st640ihg.upp
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\config.mirrorprint
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\psfonts.map
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\lw35extra_kb_kb.mapfile
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\cdj550.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_ll3.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\Fontmap.OS2
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_typ32.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\Fontmap.OSF
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\Fontmap
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\font2c.cmd
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\necp2x.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2pdf.cmd
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\acrobat_urw.mapfile
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\bj8ts06n.upp
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\pdf2ps.cmd
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_typ42.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\ps2ps
NONRESOURCE=C:\Program Files\MiKTeX\dvips\cspsfonts\csfontd.mapfile
NONRESOURCE=C:\Program Files\MiKTeX\dvips\psnfss\hlcw.map
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\printafm.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gslj.bat
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gslp.bat
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\lpgs.bat
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\stcany.upp
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\config.luc
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\pf2afm.cmd
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\st640plg.upp
NONRESOURCE=C:\Program Files\MiKTeX\dvips\config\acrobat_kb_urw.mapfile
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\cbjc600.ppd
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\stcinfo.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\markhint.ps
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_l.xpm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_m.xpm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_s.xpm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gs_t.xpm
NONRESOURCE=c:\localt~1\gs\gs6.50\lib\gsnd.bat
.
